Repository shardeum/shardeum-validator-cli, pull requests merged in 2025-05, with the labels that each got.

#68 Refactor stakableData/unstakable logic and improve state messages
  src/node-commands.ts
Labels: Review effort 3/5

#70 added sec.md
  SECURITY.md
Labels: Review effort 1/5

#71 SHARD-2433: use image digest in favour of individual repo versions
  src/node-commands.ts
  src/utils/fetch-network-data.ts
Labels: Review effort 2/5
